---
- name: Set Inventory/Authenticate with Target Server
  read_csv:
    path: win_server_list_dpc.csv
  register: server_list
  
- name: Add a host that we reach through a tunnel (Ansible 2.0 and newer)
  add_host:
    hostname: '{{ item.0 }}'
    ansible_host: '{{ item.1 }}'
    ansible_port: 5985
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985
    ansible_winrm_transport: ntlm
    name: win_servers
    with_items: '{{ server_list.list_of_dicts }}'
