to_copy_script: C:\Temp\crowd_strike\
output_execution_node: /tmp/crowd_strike_win/
SMTP_server_host: smtp.services.royalmailgroup.net
execution_path_server_status: /tmp/crowd_unreachable_servers
mail_from: AnsibleAutomation@royalmail.com
mail_to:
    - midhun.m.external@atos.net
