---
- name: Installation of Crowdstrike Agent 
  hosts: 
  gather_facts: false

  tasks:
    - name: disable windows Defender
      win_shell: Set-MpPreference-DisableRealtimeMonitoring $true
      register: defender_result

    - name: Including Services variable
      include_vars: 
        file: services_variables.yml

    - name: Check Required Services are Running
      win_service:
        name: "{{ service_name }}"
        state: started
      loop: "{{ services_to_check }}"
      register: service_result

    - name: Display the Service Status Report
      debug:
        vars: service_result
      
