---
- name: Include task to check ping status
  include_tasks: ping_status.yml

- name: Include task to start disable windows Defender
  include_tasks: disable_windows_Defender.yml

- name: Include task to install crowdstrike agent
  include_tasks: CrowdStrike_Agent_Installation.yml

- name: Include task to reporting part
  include_tasks: reporting_part.yml

